name: GoogLeNet
modules:
  entry:
    - x

  inception_1:
    cls: ComposableModel
    config: inception_block.yaml
    inp_src:
      - x
  
  inception_2:
    cls: ComposableModel
    config: inception_block.yaml
    inp_src:
      - inception_1
  
  exit:
    - inception_2